---
- name: install and start apache
  hosts: local host 
  connection: local
  become_method: sudo
  become_user: sudo
  vars:
    http_port:80
    max_clients:200

  tasks:

  - name: print out the hostname of target
    command: hostname

  - name: install httpd
    yum: name=httpd state=latest 
    template: src/srv/httpd.j2 dest=/etc/httpd.conf
    notify:
    - restart apache

  - name: start httpd
    service: name=httpd state=running
  
handlers:
  - name: restart apache
    service: name=httpd state=restarted