---
- name: install apache
  connection: local
  hosts: localhost 

  tasks:
    - name: install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - httpd tools
    
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest