---
- name: install apache
  connection: local
  hosts: localhost 

  tasks:
    - name: install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - httpd-tools
    
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    
    - name: start httpd
      service: name=httpd state=started

    - name: Install main configuration file
      template:
        src: httpd.conf.j2
        dest: "/etc/httpd.conf"
        owner: root
        group: root
        setype: httpd_config_t
      notify: restart apache
  
  
  handlers:
  - name: restart apache
    service: name=httpd state=restarted